steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t us-central1-docker.pkg.dev/development-internal-233813/tabrasa-docker/baget-fork:8.0 -f ./Dockerfile .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push us-central1-docker.pkg.dev/development-internal-233813/tabrasa-docker/baget-fork:8.0']
